title: Andrew's Blog
html_title: <img title="A" class="title-letter" src="/images/title-letter.svg" width="32" height="32" />ndrew's Blog
email: contact@andrewra.dev
description:
  Vim, Rust, Ruby, and assorted tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://andrewra.dev"
twitter_username: AndrewRadev
github_username:  AndrewRadev
excerpt_separator: '<!-- more -->'

permalink: /:year/:month/:day/:title/

paginate: 10

# Exclude some service files:
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'deploy'

# Include additional plugins
plugins:
  - 'jekyll-paginate'
