title: Andrew's Blog
email: andrey.radev@gmail.com
description:
  Just another programming blog with an uninspired title
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewradev.com"
twitter_username: AndrewRadev
github_username:  AndrewRadev

# Build settings
markdown: kramdown
