title: Andrew's Blog
email: andrey.radev@gmail.com
description:
  Just another programming blog with an uninspired title
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrewradev.com"
twitter_username: AndrewRadev
github_username:  AndrewRadev
excerpt_separator: '<!-- more -->'

permalink: /:year/:month/:day/:title/

paginate: 10

# Exclude some service files:
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'deploy'

# Build settings
markdown: redcarpet
highlighter: rouge
